In [31]:
import torch
import numpy as np


In [14]:
Image = torch.randn((256,256,3))
Scale = torch.tensor([0.5, 1.5, 1])

print(Image.shape)
print(Scale.shape)

torch.Size([256, 256, 3])
torch.Size([3])


In [15]:
Image

tensor([[[-0.3074,  0.8897, -1.0785],
         [ 0.1653,  0.0955,  0.4745],
         [-0.8885, -0.5066,  0.4441],
         ...,
         [-0.6530,  0.0617, -1.4570],
         [ 0.7606,  1.0855, -1.0595],
         [-0.4463, -0.5083, -1.1160]],

        [[-1.6276, -0.8496, -1.8173],
         [-0.4902, -0.0084,  1.6516],
         [-1.0016,  0.4214, -1.9938],
         ...,
         [ 0.1142, -0.4086, -0.0222],
         [ 0.9769,  0.2022,  2.1875],
         [ 0.6793, -0.4075, -0.5223]],

        [[-1.1438,  1.0402, -1.0392],
         [ 1.0573, -1.8691,  1.0115],
         [-0.2694,  0.3307,  1.2699],
         ...,
         [ 1.5941,  1.4739,  1.2558],
         [-0.0762, -0.4922, -0.3753],
         [ 0.6467, -1.3935, -1.2177]],

        ...,

        [[-1.5051, -1.1134,  0.6332],
         [-0.6970,  0.8001,  0.2443],
         [-1.5832, -0.9591,  0.2247],
         ...,
         [ 0.7673, -0.4148,  0.1455],
         [ 1.7792,  0.9201,  0.2438],
         [ 0.5394, -0.2879, -0.4208]],

        [[

In [16]:
Image*Scale

tensor([[[-0.1537,  1.3346, -1.0785],
         [ 0.0826,  0.1433,  0.4745],
         [-0.4442, -0.7599,  0.4441],
         ...,
         [-0.3265,  0.0925, -1.4570],
         [ 0.3803,  1.6282, -1.0595],
         [-0.2231, -0.7624, -1.1160]],

        [[-0.8138, -1.2744, -1.8173],
         [-0.2451, -0.0125,  1.6516],
         [-0.5008,  0.6321, -1.9938],
         ...,
         [ 0.0571, -0.6129, -0.0222],
         [ 0.4885,  0.3033,  2.1875],
         [ 0.3396, -0.6113, -0.5223]],

        [[-0.5719,  1.5603, -1.0392],
         [ 0.5286, -2.8036,  1.0115],
         [-0.1347,  0.4961,  1.2699],
         ...,
         [ 0.7971,  2.2109,  1.2558],
         [-0.0381, -0.7383, -0.3753],
         [ 0.3234, -2.0902, -1.2177]],

        ...,

        [[-0.7525, -1.6701,  0.6332],
         [-0.3485,  1.2001,  0.2443],
         [-0.7916, -1.4386,  0.2247],
         ...,
         [ 0.3837, -0.6222,  0.1455],
         [ 0.8896,  1.3802,  0.2438],
         [ 0.2697, -0.4319, -0.4208]],

        [[

In [17]:
t = torch.arange(20, dtype = float).reshape(5,4)

In [18]:
t

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=torch.float64)

In [19]:
t, torch.mean(t, axis = 0) # Mean across the rows, that are the first dimension!!


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([ 8.,  9., 10., 11.], dtype=torch.float64))

In [20]:
torch.mean(t, axis = 1) # Mean across the columns, that are the SECOND dimension!

tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000], dtype=torch.float64)

In [21]:
t = torch.randn(5, 256, 256, 3)

Take the mean across the batch (size 5), different images!

It will take the mean of the batchs. For example, it will look each individual channel (red, green, blue) and compute the mean of these channels using the different images

In [22]:
torch.mean(t, axis = 0).shape

torch.Size([256, 256, 3])

Take the mean across the color channels. It could be used to get something like the brightness of an image.

In [23]:
torch.mean(t, axis = -1).shape

torch.Size([5, 256, 256])

# Where Pytorch Differs from Numpy?

In [24]:
x = torch.tensor([[5.,8.],[4.,6.]], requires_grad = True)

In [25]:
x

tensor([[5., 8.],
        [4., 6.]], requires_grad=True)

In [26]:
y = x.pow(3).sum() + x.pow(2).sum()

In [27]:
3*x.pow(2) + 2*x

tensor([[ 85., 208.],
        [ 56., 120.]], grad_fn=<AddBackward0>)

In [28]:
y

tensor(1058., grad_fn=<AddBackward0>)

In [29]:
y.backward()
x.grad

tensor([[ 85., 208.],
        [ 56., 120.]])